"""initial migration

Revision ID: 4eefbdbe3f29
Revises: 
Create Date: 2025-10-30 08:10:54.606727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eefbdbe3f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first without foreign keys
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Create teams table
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)

    # Add foreign key from users to teams
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'])
    op.create_table('secrets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('iv', sa.String(), nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=False),
    sa.Column('current_views', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('attachment_size', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_created_by_id'), 'secrets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_secrets_expires_at'), 'secrets', ['expires_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'TEAM', 'ENTERPRISE', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('usage_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('secrets_created_this_month', sa.Integer(), nullable=False),
    sa.Column('secret_requests_this_month', sa.Integer(), nullable=False),
    sa.Column('attachment_bytes_this_month', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('secret_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_access_logs_secret_id'), 'access_logs', ['secret_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_secret_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_accessed_at'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_secrets_expires_at'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_created_by_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
